server {
    listen 80;
    server_name _;

    client_max_body_size 10m;

    location / {
        proxy_pass http://web-client:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /identity/ {
        proxy_pass http://gateway:8080/identity/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /equipment/ {
        proxy_pass http://gateway:8080/equipment/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /maintenance/ {
        proxy_pass http://gateway:8080/maintenance/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /files/ {
        proxy_pass http://gateway:8080/files/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /reports/ {
        proxy_pass http://gateway:8080/reports/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /hubs/ {
        proxy_pass http://gateway:8080/hubs/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
